### ISSUE TITLE
cr_cn works with bibtex but not with citeproc-json

### ISSUE THREAD

**Issue by nickbart1980** [ropensci/rcrossref#62] opened 2015-04-08 22:01 UTC
```r
> cat(cr_cn(dois = "10.1002/app.27716", format = "bibtex"))
@article{Tang_2008,
	doi = {10.1002/app.27716},
	url = {http://dx.doi.org/10.1002/app.27716},
	year = 2008,
	publisher = {Wiley-Blackwell},
	volume = {108},
	number = {3},
	pages = {1490--1495},
	author = {Qunwei Tang and Jianming Lin and Jihuai Wu},
	title = {The preparation and electrical conductivity of polyacrylamide/graphite conducting hydrogel},
	journal = {Journal of Applied Polymer Science}
}
```

```r
> cat(cr_cn(dois = "10.1002/app.27716", format = "citeproc-json"))
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 1 (type 'list') cannot be handled by 'cat'
```

**Comment by sckott** [comment] 2015-04-08 22:08
thanks @nickbart1980 

`cr_cn(dois = "10.1002/app.27716", format = "bibtex")` returns a character string with newlines, so using `cat()` pretty prints the text, but `cr_cn(dois = "10.1002/app.27716", format = "citeproc-json")` returns a list, which `cat()` can not process. 

anyway, that's not really a bug, but the intended behavior. 

Do you want `citeproc-json` to be presented differently than a list?

**Comment by nickbart1980** [comment] 2015-04-09 07:43
Thank you. – Well, I was expecting this format, as used by citeproc-js (Zotero etc.), pandoc-citeproc and other citeprocs; see https://github.com/citation-style-language/schema/blob/master/csl-data.json:

```
[
  {
    "DOI": "10.1002/app.27716",
    "URL": "http://dx.doi.org/10.1002/app.27716",
    "author": [
      {
        "family": "Tang",
        "given": "Qunwei"
      },
      {
        "family": "Lin",
        "given": "Jianming"
      },
      {
        "family": "Wu",
        "given": "Jihuai"
      }
    ],
    "container-title": "Journal of Applied Polymer Science",
    "id": "Tang_2008",
    "issue": "3",
    "issued": {
      "date-parts": [
        [
          2008
        ]
      ]
    },
    "page": "1490-1495",
    "publisher": "Wiley-Blackwell",
    "title": "The preparation and electrical conductivity of polyacrylamide/graphite conducting hydrogel",
    "type": "article-journal",
    "volume": "108"
  }
]
```

Is this possible?

**Comment by sckott** [comment] 2015-04-09 16:07
hey @nickbart1980 - okay, adding a parameter to the fxn for this...

**Comment by sckott** [comment] 2015-04-09 16:19
@nickbart1980 okay, reinstall from github `devtools::install_github("ropensci/rcrossref")` and try e.g., 

```r
cr_cn(dois = "10.1002/app.27716", format = "citeproc-json", raw = TRUE)
```

**Comment by nickbart1980** [comment] 2015-04-10 09:06
Thank you. However, as it turns out, this format is not really citeproc JSON – and thus should be renamed to avoid confusion.
See kjw, at https://github.com/CrossRef/rest-api-doc/issues/43: “The default response type of the API is not citeproc JSON. It is a format that is based on citeproc JSON but, as you've noted, differs in some ways that make it incompatible with citeproc tools.”

kjw also notes: “We do provide a more standard citeproc JSON:
`http://api.crossref.org/works/10.1108/02683940810904367/transform/application/vnd.citationstyles.csl+json`
This should successfully run through citeproc js. Where it does not, I would want to fix it immediately.”

Currently, this still contains bugs that make it unusable, but, if anything, this latter thing would be the “citeproc JSON” or “CSL JSON”, comparable to bibtex or RIS in functionality, I was expecting.

Thanks again.

**Comment by sckott** [comment] 2015-04-10 15:58
thanks @nickbart1980  - didn't know they did content negotiation with that API, i use `http://dx.doi.org` in `cr_cn()` function, and docs at http://www.crosscite.org/cn/  I've opened an issue CrossRef/rest-api-doc#52 to ask about whether we should use the new API for this stuff

I will rename the type returned by the current `citeproc-json` to something else, and use that trick to give proper data

**Comment by sckott** [comment] 2015-04-10 16:27
@nickbart1980 reinstall. See examples https://github.com/ropensci/rcrossref/blob/master/R/cr_cn.r#L30-L31

**Comment by mfenner** [comment] 2015-04-10 16:36
Interesting discussion. Similar to the CrossRef REST API I am also using Citeproc JSON in the Lagotto API (e.g. http://labs.lagotto.io/api/works/doi:10.1371/journal.pone.0055723). Stricly speaking it is not correct Citeproc JSON, as I am using other attributes in addition to the standard Citeproc attributes (similar to CrossRef), but the Citeproc JSON spec doesn't allow that.

There has been discussion on the Xbiblio (CSL) mailing list about extending Citeproc JSON, so I hope that is the overall direction this will go. I personally don't like content negotiation too much in this case, as it makes the API more complicated.

**Comment by sckott** [comment] 2015-04-10 17:02
> I personally don't like content negotiation too much in this case, as it makes the API more complicated.

which case? 

I hadn't thought about whether the citeproc you returned from Lagotto was proper or not. No one's complained about that I've heard, but maybe you have heard it

**Comment by mfenner** [comment] 2015-04-10 17:22
> which case?

Multiple flavors of JSON. It seems to me that the CrossRef REST API is the direction CrossRef is going, and it provides much more flexibility that the content negotation API (which is basically for single DOIs).

What I want to do in one of the next Lagotto releases is to use CIteproc.js in the admin frontend, and this will show me how consistent my JSON is with Citeproc JSON. The biggest problem until now was missing metadata (container-title, authors, etc.), but that is fixed in the next release.

**Comment by sckott** [comment] 2015-04-10 17:55
Right, it does make sense to go with the Crossref REST API.  Thinking about doing that.

**Comment by mfenner** [comment] 2015-04-11 06:19
Scott, it seems you can also use the CrossRef REST API with content negotation (from the documentation at http://www.crosscite.org/cn/):

```
curl http://api.crossref.org/works/10.5555/12345678/transform/application/x-bibtex
```

This should give you a nice transition path to the REST API.

**Comment by sckott** [comment] 2015-04-13 20:38
thanks @mfenner

**Comment by sckott** [comment] 2015-05-20 00:16
considering this done

**Closed by sckott** 2015-05-20 00:16 UTC
